### ISSUE TITLE
While deleting the launcher , the fatal error showing

### ISSUE THREAD

**Issue by Mercypaul27** [wployalty/wll-loyalty-launcher#10]
Step to reproduce
step 1: Activate the brand add-on
step 2: Delete the launcher this error showing.
![image](https://github.com/user-attachments/assets/e9846ab5-f2fa-4817-af70-e09900ac1cd3)
![image](https://github.com/user-attachments/assets/1326fbf5-751d-452e-a8ea-21aff5e3a339)

**Comment by sabhari-krr** [comment]
Fixed.

**Comment by Mercypaul27** [comment]
Still Not Fixed
![image](https://github.com/user-attachments/assets/ac18a9ea-0f8a-43ad-9694-52915403b59d)

**Comment by sabhari-krr** [comment]
Not an issue

**Comment by Mercypaul27** [comment]
Fixed

![Image](https://github.com/user-attachments/assets/7883cb3e-ad84-4660-b194-3a15d3d1cb19)
